services:
  scraper:
    build: ./scraper
    environment:
      #- MODO_ALERTAS=generar # comentar para usar los eventos ya scrapeados
      - MODO_ALERTAS=usar_existentes
    depends_on: 
      - mongodb

  mongodb:
    image: mongo:4.4
    restart: always
    hostname: mongodb
    environment:
      - MONGO_INITDB_DATABASE=sd_db
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    logging:
      driver: "none"
      
  filtro_homo:
    build: ./filtro_homo
    volumes:
      #- ./data-pig/calles:/app/salida_por_calle
      #- ./data-pig/comuna:/app/salida_por_comuna
      - ./data-pig/calles:/app/salidas_calle
      - ./data-pig/comunas:/app/salidas_comuna
    depends_on:
      - mongodb
      - scraper
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.0
    deploy:
      resources:
        limits:
          memory: 1GB
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false

  kibana:
    image: docker.elastic.co/kibana/kibana:9.0.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  redis:
    image: "redis:latest"
    hostname: rediss
    ports:
      - 6379:6379
    volumes:
      - ./data:/data

  cache: 
    build: ./cache
    hostname: cachechito
    ports:
      - 9090:9090
    environment:
      #- EVICTION_POLICY=allkeys-random
      - EVICTION_POLICY=allkeys-lru
    depends_on:
      - redis
